### ISSUE TITLE
Not working for nuxt2.9.2

### ISSUE THREAD

**Issue by j4tmr** [nuxt-community/blog-module#31]
<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/blog-module/issues/c12">#c12</a>)</em></sub></div>

**Comment by devunion** [comment]
The same problem:

 It stopped to work with the next error:

dep.getResourceIdentifier is not a function                                                                                                                                                                                                           22:18:10

  at addDependency (node_modules\webpack\lib\Compilation.js:796:30)
  at iterationOfArrayCallback (node_modules\webpack\lib\Compilation.js:208:3)
  at addDependenciesBlock (node_modules\webpack\lib\Compilation.js:816:5)
  at Compilation.processModuleDependencies (node_modules\webpack\lib\Compilation.js:827:4)
  at afterBuild (node_modules\webpack\lib\Compilation.js:954:15)
  at buildModule.err (node_modules\webpack\lib\Compilation.js:998:11)
  at callback (node_modules\webpack\lib\Compilation.js:734:5)
  at module.build.error (node_modules\webpack\lib\Compilation.js:782:12)
  at handleParseResult (node_modules\webpack\lib\NormalModule.js:478:12)
  at doBuild.err (node_modules\webpack\lib\NormalModule.js:500:6)
  at runLoaders (node_modules\webpack\lib\NormalModule.js:358:12)
  at node_modules\loader-runner\lib\LoaderRunner.js:373:3
  at iterateNormalLoaders (node_modules\loader-runner\lib\LoaderRunner.js:214:10)
  at Array.<anonymous> (node_modules\loader-runner\lib\LoaderRunner.js:205:4)
  at Storage.finished (node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
  at provider (node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)

C:\work\vitya\my_progs\GoldStorage\src\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
